server:
  port: 8281
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: house-feign
  thymeleaf:
    encoding: UTF-8
    servlet:
      content-type: text/html
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300
      repositories:
        enabled: true