server:
  port: 8086
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/1809
  application:
    name: springcloud-house-web

redis:
  host: 127.0.0.1
  port: 6379
  jedis:
    pool:
      max-idle: 8
      min-idle: 0

feign:
  hystrix:
    enabled: true

  thymeleaf:
    encoding: UTF-8
    servlet:
      content-type: text/html



