server:
  port: 8280
  max-http-header-size: 20480
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.164:3306/house?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  application:
    name: house-provider


  #mybatis.mapper-locations=classpath:mapper/*.xml
  #spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
  #spring.datasource.url=jdbc:mysql://localhost:3306/1801?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8
  #spring.datasource.username=root
  #spring.datasource.password=root
  #编码格式
  #spring.thymeleaf.encoding=UTF-8
  #内容展示类型
  #spring.thymeleaf.servlet.content-type=text/html
  mybatis:
    mapper-locations: classpath:mapper/*.xml


