server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: service-customer
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.164:3306/house?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  thymeleaf:
    servlet:
      content-type: text/html
    encoding: UTF-8
mybatis:
  mapper-locations: classpath:mapper/*.xml


