server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: order-feign
  thymeleaf:
    servlet:
      content-type: text/html
    encoding: UTF-8

